"""
This is the code used for evaluating the generated answers and compute the accuracy.
It can return high-level avg accuracy (ID, VE, FE) or the one corresponding to each 
counting number.
You can run the code in the following way:
python test_acc.py --log_file './answer-output-finetune-multimodal-num-vision-50-text-100.log' --output_type num
"""
import argparse
import json
import re

def finalize_accuracy_bucket(bucket, output_type, per_num_black = True):
    return {
        "correct": bucket["correct"],
        "total": bucket["total"],
        "accuracy_percent": 100.0 * bucket["correct"] / bucket["total"],
        "average_error": bucket["sum_abs_error"] / bucket["total"] if output_type == "num" and per_num_black else None   #only returned when output_type is num and is asked detailed per_num_black accuracy, otherwise None
    }


def domain_name(num_black, vision_boundary, text_boundary, max_num_black):
    if 0 <= num_black <= vision_boundary:
        return "in_domain"
    if vision_boundary < num_black <= text_boundary:
        return "visual_extrapolation"
    if text_boundary < num_black <= max_num_black:
        return "full_extrapolation"
    
    raise ValueError('No category assigned!')
    return


def compute_accuracy_summary(log_file, output_type, vision_boundary, text_boundary, max_num_black):
    per_num_black = {}
    domains = {
        "in_domain": {"correct": 0, "total": 0},
        "visual_extrapolation": {"correct": 0, "total": 0},
        "full_extrapolation": {"correct": 0, "total": 0},
    }

    with open(log_file, "r", encoding="utf-8") as handle:
        for _, line in enumerate(handle, start=1):

            entry = json.loads(line)

            num_black = int(entry["num_black"])
            groundtruth = entry["groundtruth"]
            prediction = None
            if output_type == "num":
                prediction = int(entry["generated_answer"]) if entry["generated_answer"] is not None and entry["generated_answer"] != "" else 0
            elif entry["generated_answer"] is not None and entry["generated_answer"] != "":
                prediction = entry["generated_answer"].lower() == "true"
            is_correct = (prediction == groundtruth)
            abs_error = abs(prediction - groundtruth) if output_type == "num" else None

            per_num_black.setdefault(num_black, {"correct": 0, "total": 0, "sum_abs_error": 0.0})
            per_num_black[num_black]["total"] += 1
            if is_correct:
                per_num_black[num_black]["correct"] += 1
            if abs_error is not None:
                per_num_black[num_black]["sum_abs_error"] += abs_error


            domain = domain_name(
                num_black,
                vision_boundary=vision_boundary,
                text_boundary=text_boundary,
                max_num_black=max_num_black,
            )
            domains[domain]['total'] += 1
            if is_correct:
                domains[domain]['correct'] += 1

    return {
        "ranges": {
            "in_domain": [0, vision_boundary],
            "visual_extrapolation": [vision_boundary + 1, text_boundary],
            "full_extrapolation": [text_boundary + 1, max_num_black],
        },
        "domains": {
            name: finalize_accuracy_bucket(bucket, output_type, False)
            for name, bucket in domains.items()
        },
        "per_num_black": {
            str(num_black): finalize_accuracy_bucket(bucket, output_type, True)
            for num_black, bucket in sorted(per_num_black.items())
        },
    }


def compute_generated_number_frequency(log_file, min_num_black=50, max_num_black=99):
    generated_counts = {}
    total = 0

    with open(log_file, "r", encoding="utf-8") as handle:
        for _, line in enumerate(handle, start=1):
            entry = json.loads(line)
            num_black = int(entry["num_black"])
            if not (min_num_black <= num_black <= max_num_black):
                continue

            generated_answer = entry["generated_answer"]
            if generated_answer is None or generated_answer == "":
                generated_number = "empty"
            else:
                generated_number = int(generated_answer)
            generated_counts[generated_number] = generated_counts.get(generated_number, 0) + 1
            total += 1

    return dict(
        sorted(
            (
                (generated_number, 100.0 * count / total)
                for generated_number, count in generated_counts.items()
            ),
            key=lambda item: (item[0] == "empty", item[0]),
        )
    ) if total > 0 else {}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compute accuracy from the JSONL log generated by test_model.py."
    )
    parser.add_argument("--log_file", required=True, help="Path to test_model.py JSONL output.")
    parser.add_argument("--output_type", choices=("num", "tf"), required=True)
    parser.add_argument("--vision_boundary", type=int, default=49)
    parser.add_argument("--text_boundary", type=int, default=99)
    parser.add_argument("--max_num_black", type=int, default=120)
    return parser.parse_args()


def main():
    args = parse_args()

    summary = compute_accuracy_summary(
        log_file=args.log_file,
        output_type=args.output_type,
        vision_boundary=args.vision_boundary,
        text_boundary=args.text_boundary,
        max_num_black=args.max_num_black,
    )

    # print(summary['per_num_black'])
    # This is for outputing the accuracy percentage for each counting number.
    # for num_black, bucket in sorted(summary["per_num_black"].items(), key=lambda item: int(item[0])):
    #     print((int(num_black), bucket["accuracy_percent"]))

    # This is for outputing the average error for each counting number.
    # for num_black, bucket in sorted(summary["per_num_black"].items(), key=lambda item: int(item[0])):
    #     print((int(num_black), bucket["average_error"]))

    # This is for outputing the generated wrong number frequency in VE domain
    # if args.output_type == "num":
    #     generated_frequency = compute_generated_number_frequency(
    #         log_file=args.log_file,
    #         min_num_black=50,
    #         max_num_black=99,
    #     )
    #     for generated_number, percentage in generated_frequency.items():
    #         print((generated_number, percentage))


if __name__ == "__main__":
    main()
